---

domain: openfoodnetwork.net
host_id: us-prod
rails_env: production

admin_email: ofn-usa@openfoodnetwork.net

mail_domain: openfoodnetwork.net

unicorn_workers: 3

certbot_domains:
  - openfoodnetwork.net
  - www.openfoodnetwork.net

# Size in bytes. You can also use units like 1G, 512MiB or 1000KB. See: `man fallocate`
# The default is `false`, not installing a swapfile.
swapfile_size: 1G

postgres_listen_addresses:
  - '*'

custom_hba_entries:
  - { type: hostssl, database: "{{ db }}", user: zapier, address: '54.86.9.50/32', auth_method: md5 }

enable_rails_apm: "true"

beta_testers:
  - andy@andybrett.com
