---

domain: openfoodnetwork.be
host_id: be-prod
rails_env: production

admin_email: admin@openfoodnetwork.be

mail_domain: openfoodnetwork.be

certbot_domains:
  - openfoodnetwork.be
  - www.openfoodnetwork.be

attachment_url: ofn-belgium.s3.us-east-1.amazonaws.com
